name: thunderseg
channels:
    - defaults
    - conda-forge
    - pytorch
    - nvidia
dependencies:
    - python=3.11.9
    - numpy=1.26.4
    - pandas=2.2.3
    - geopandas=1.0.1
    - rasterio=1.4.1
    - opencv=4.10.0
    - colorama=0.4.6
    - conda-forge::sqlite=3.46.1
    - pytorch=2.4.1
    - torchvision=0.19.0
    - pytorch-cuda=12.4
    - albumentations=1.4.20
    - lightning=2.4.0
    - pip
    - pip:
        - pycocotools
        - tensorboardX
        - tomli_w
