name: thunderseg
channels:
    - defaults
    - conda-forge
    - pytorch
    - nvidia
dependencies:
    - python=3.11.9
    - numpy=1.26.4
    - pandas=2.2.3
    - geopandas=1.0.1
    - rasterio=1.4.1
    - opencv=4.10.0
    - colorama=0.4.6
    - conda-forge::sqlite=3.46.1
    - albumentations=1.4.20
    - pip
    - pip:
        - pycocotools
        - tensorboard
        - tomli_w
        - torch==2.4.1
        - torchvision==0.19.1
        - lightning==2.4.0
        - fiftyone==1.3.1
