site_name: Thunderseg
repo_url: https://github.com/jldz9/thunderseg
repo_name: jldz9/thunderseg
site_url: https://jldz9.github.io/thunderseg/
theme:
  name: material
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - toc.follow
    - navigation.top
    - search.suggest
    - search.highlight
    - header.autohide
    - content.code.copy
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      toggle:
        icon: material/weather-night
        name: switch to dark mode
    - media: "(prefers-color-scheme: light)"
      scheme: slate
      primary: black
      toggle:
        icon: material/weather-sunny
        name: switch to light mode
  icon:
    repo: fontawesome/brands/github
  

nav: 
  - Home: index.md
  - Getting Start: 
    - Installation: getting_start/index.md
    - Basic Usage: getting_start/basic_usage.md
  - Structure: 
    - Main Program: flowchart/main_program.md
  - About: about.md

extra:
  social:
    - icon: fontawesome/solid/envelope
      link: jiaweiliwork@outlook.com
      name: Email me
    - icon: fontawesome/brands/discord
      link: https://discord.gg/RJJM42MBUU
      name: Discord
  version:
    provider: mike

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.details:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - tables
  - md_in_html
  - pymdownx.blocks.caption
  

plugins:
  - search
